### ISSUE TITLE
Paridisec Integration testing

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/TLCMapViews#5]
From John Ferlito 13/7

I've updated to v2 URLs.

I'm getting an issue with the collection level (first three maps), same geojson was working fine with the v1.

Could you get your team to take a look and see if they can work out what's breaking?

The console has this error config-loader.js:355 TypeError: Cannot read properties of undefined (reading 'type')
    at buildDefaultPopup (config-loader.js:452:26)
    at config-loader.js:204:50
    at Array.forEach (<anonymous>)
    at config-loader.js:195:35

https://catalog.paradisec.org.au/tlcmap

**Comment by MufengNiu** [comment]
Hi @IanMcCrabb , The problem occurs because of the JSON data feed . For now the code is expecting all the geojson data to be valid however there is some empty data that cause this issue: 
![Screenshot 2023-07-13 at 19 11 19](https://github.com/HughCraig/TLCMapViews/assets/51284623/9c8b263f-a1bf-4308-bf30-ba04b20c0068)

**Comment by IanMcCrabb** [comment]
Let's discuss this morning with Yang.  Not sure whether we should accommodate empty data...

**Comment by MufengNiu** [comment]
> Let's discuss this morning with Yang. Not sure whether we should accommodate empty data...

Hi @IanMcCrabb ,  Yang has confirmed that we are not expected to handle data validation within our system. It will be the responsibility of the data provider to ensure the JSON input is valid.

**Comment by IanMcCrabb** [comment]
Thanks @MufengNiu, Ill liaise with the client
